// <auto-generated />
using System;
using HomeBillings.Entradas.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBillings.Usuario.API.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeBillings.Usuario.API.Domain.Entities.Address", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(true)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("ID");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("BAIRRO");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RUA");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CEP");

                    b.HasKey("Id");

                    b.ToTable("ENDERECOS", "dbo");
                });

            modelBuilder.Entity("HomeBillings.Usuario.API.Domain.Entities.Family", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(true)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("CreatedIn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOME");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TIPO_PESSOA");

                    b.HasKey("Id");

                    b.ToTable("FAMILIAS", "dbo");
                });

            modelBuilder.Entity("HomeBillings.Usuario.API.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(true)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AddressId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("IDADE");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SOBRENOME");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("Person")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TIPO_PESSOA");

                    b.Property<string>("PersonRegister")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasColumnName("REGISTRO_PESSOA");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("FamilyId");

                    b.ToTable("USUARIOS", "dbo");
                });

            modelBuilder.Entity("HomeBillings.Usuario.API.Domain.Entities.User", b =>
                {
                    b.HasOne("HomeBillings.Usuario.API.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBillings.Usuario.API.Domain.Entities.Family", "Family")
                        .WithMany("Users")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("HomeBillings.Usuario.API.Domain.Entities.Family", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
