// <auto-generated />
using System;
using HomeBillings.Entradas.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBillings.Entradas.API.Migrations
{
    [DbContext(typeof(EntryContext))]
    [Migration("20250301223447_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeBillings.Entradas.API.Domain.Entities.Categoria.Category", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(true)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("SIGLA");

                    b.Property<DateTimeOffset>("CreatedIn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("CATEGORIAS", "dbo");
                });

            modelBuilder.Entity("HomeBillings.Entradas.API.Domain.Entities.Entrada.Entry", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(true)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("ID");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("CATEGORIA_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTimeOffset>("EntryDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DATA_ENTRADA");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ENTRADAS", "dbo");
                });

            modelBuilder.Entity("HomeBillings.Entradas.API.Domain.Entities.Entrada.Entry", b =>
                {
                    b.HasOne("HomeBillings.Entradas.API.Domain.Entities.Categoria.Category", "Category")
                        .WithMany("Entries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HomeBillings.Entradas.API.Domain.Entities.Categoria.Category", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
